### ISSUE TITLE
Solution time alt text for on hover circles

### ISSUE THREAD

**Issue by sim642** [amochtar/aoc-ranking#2]
As of the new update hovering shows per-day ranks. It would be nice if each of those per-day rank circles had an alt text which shows the corresponding solution time. Like https://adventofcode.com/2019/leaderboard/self shows for oneself, it would be neat to quickly see the solution times for other people on the leaderboard as well.

**Comment by amochtar** [comment]
Thanks for the suggestion! Yes, that's definitely something I'd like to add, together with scores per part, and total score so far. I'll see if I can hack something together :)
